CREATE TABLE T_PARTY_CONTACT_TEMP
   (	
	ADDRESS_ID NUMBER(19,0) NOT NULL, 
	ADDRESS_1 VARCHAR2(600 BYTE), 
	 PRIMARY KEY (ADDRESS_ID)
) WITH "template=REPLICATED,backups=0,CACHE_NAME=PartyContactTemp, ATOMICITY=ATOMIC";


